# ==========================================
# 1. CẤU HÌNH SERVER & API GIAO DIỆN
# ==========================================
server.port=8080

# ==========================================
# 2. CẤU HÌNH KẾT NỐI ĐƯỜNG DẪN MYSQL CHUNG
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/n5_kawaii_english?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# 3. KÍCH HOẠT PROFILE CỤC BỘ (TEAMWORK SOLVED)
# ==========================================
# Ép Spring Boot quét thêm file 'application-local.properties' để nạp mật khẩu riêng biệt
spring.profiles.active=local

# ==========================================
# 4. BẢO VỆ TOÀN VẸN ACTIVE DATABASE
# ==========================================
# Nghiêm cấm Hibernate tự ý can thiệp, sửa đổi cấu hình bảng vật lý.
# Giữ an toàn 100% cho hệ thống Triggers, Stored Procedures và Views.
spring.jpa.hibernate.ddl-auto=none

# Hiển thị và định dạng các câu lệnh SQL truy vấn dưới Terminal để tiện Debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true